USE QLBH
GO
--Tính Tổng Tiền Đơn Hàng
CREATE OR ALTER 
FUNCTION UF_TONGTIEN (@MADH VARCHAR(10))
RETURNS MONEY
AS
BEGIN
	RETURN (SELECT PHIVANCHUYEN FROM DONDATHANG WHERE MADH = @MADH) + 
			(SELECT SUM(MA.GIA * CT.SLMON)
			FROM CHITIETDONDATHANG CT 
			JOIN MONAN MA ON CT.MAMA = MA.MAMA AND CT.MADT = MA.MADT
			WHERE CT.MADH = @MADH)
END
GO

--ĐĂNG KÝ TÀI KHOẢN------------------------------------------------------------
CREATE OR ALTER
PROC SP_DANGKYTAIKHOAN
	@USERID VARCHAR(100),
	@PASSWORD VARCHAR(100),
	@PASSWORDCHECK VARCHAR(100),
	@LOAITK INT
AS
BEGIN
	IF @USERID = '' OR @PASSWORD = '' OR @PASSWORDCHECK = '' OR @LOAITK = ''
	BEGIN
		PRINT N'Không nhập đầy đủ thông tin để đăng ký'
		RETURN
	END
	IF @LOAITK < 0 OR @LOAITK > 4
	BEGIN
		PRINT N'Loại tài khoản không phù hợp'
		RETURN
	END

	IF EXISTS (SELECT '1' FROM TAIKHOAN WHERE TENTK = @USERID)
	BEGIN
		PRINT N'Tên tài khoản đã tồn tại'
		RETURN
	END

	IF @PASSWORD <> @PASSWORDCHECK
	BEGIN
		PRINT N'Mật Khẩu và Nhập Lại Mật Khẩu không trùng khớp'
		RETURN
	END

	--TẠO MÃ TÀI KHOẢN
	DECLARE @MATK VARCHAR(10) = 'TK'
	WHILE @MATK = 'TK' OR @MATK IN ( SELECT MATK FROM TAIKHOAN)
	BEGIN
		 SET @MATK += CAST((FLOOR(RAND()*(100000-0+1)+0)) AS VARCHAR(98))
	END
	--TẠO MÃ CHO MỖI PHÂN HỆ
	DECLARE @MAPHANHE VARCHAR(10)
	IF @LOAITK = 2
		SET @MAPHANHE = 'DT'
	ELSE IF @LOAITK = 3
		SET @MAPHANHE = 'KH'
	ELSE
		SET @MAPHANHE = 'TX'
	WHILE (SELECT LEN(@MAPHANHE)) = 2 OR @MATK IN ( SELECT MATK FROM TAIKHOAN)
	BEGIN
		 SET @MAPHANHE += CAST((FLOOR(RAND()*(100000-0+1)+0)) AS VARCHAR(8))
	END

	--THÊM TÀI KHOẢN
	INSERT INTO TAIKHOAN VALUES(@MATK,@USERID,@PASSWORD,@LOAITK)
	EXEC SP_ADDLOGIN @USERID, @PASSWORD,'QLBH'
	--THÊM PHÂN HỆ
	IF @LOAITK = 2
	BEGIN
		INSERT INTO DOITAC(MADT, MATK) VALUES(@MAPHANHE, @MATK)
		EXEC SP_ADDUSER @USERID, @MAPHANHE, 'R_DOITAC'
	END
	ELSE IF @LOAITK = 3
	BEGIN
		INSERT INTO KHACHHANG(MAKH, MATK) VALUES(@MAPHANHE, @MATK)
		EXEC SP_ADDUSER @USERID, @MAPHANHE, 'R_KHACHHANG'
	END
	ELSE
	BEGIN
		INSERT INTO TAIXE(MATX, MATK) VALUES(@MAPHANHE, @MATK)
		EXEC SP_ADDUSER @USERID, @MAPHANHE, 'R_TAIXE'
	END
	IF @@ERROR <> 0 
		PRINT N'Đăng ký không thành công'
	ELSE
		PRINT N'Đăng ký thành công'
END
GO

--ĐĂNG NHẬP------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DANGNHAP
	@USERID VARCHAR(100),
	@PASSWORD VARCHAR(100)
AS
BEGIN
	DECLARE @MAPHANHE VARCHAR(10)
	DECLARE @LOAITK INT = (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @USERID AND MATKHAU = @PASSWORD)
	DECLARE @MATK VarChar(10) = (SELECT MATK FROM TAIKHOAN WHERE TENTK = @USERID AND MATKHAU = @PASSWORD)
	IF @LOAITK = 0
	BEGIN
		SET @MAPHANHE = (SELECT MANV FROM NHANVIEN WHERE MATK = @MATK)
	END
	ELSE IF @LOAITK = 1
	BEGIN
		SET @MAPHANHE = (SELECT MANV FROM NHANVIEN WHERE MATK = @MATK)
	END
	ELSE IF @LOAITK = 2
	BEGIN
		SET @MAPHANHE = (SELECT MADT FROM DOITAC WHERE MATK = @MATK)
	END
	ELSE IF @LOAITK = 3
	BEGIN
		SET @MAPHANHE = (SELECT MAKH FROM KHACHHANG WHERE MATK = @MATK)
	END
	ELSE
	BEGIN
		SET @MAPHANHE = (SELECT MATX FROM TAIXE WHERE MATK = @MATK)
	END
	
	IF @USERID = ''OR @PASSWORD = ''
	BEGIN
		PRINT N'Không nhập đầy đủ thông tin để đăng nhập'
		RETURN 2
	END
	IF NOT EXISTS (SELECT * FROM TAIKHOAN WHERE TENTK = @USERID)
	BEGIN
		PRINT N'Tên tài khoản không tồn tại'
		RETURN 3
	END

	IF @PASSWORD <> (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @USERID)
	BEGIN
		PRINT N'Mật Khẩu Sai'
		RETURN 4
	END
	IF @@ERROR <> 0 
		PRINT N'Đăng nhập không thành công'
	ELSE
		PRINT N'Đăng nhập thành công'
		RETURN 5
END
GO

--CẬP NHẬT THÔNG TIN TÀI KHOẢN---------------------------------------------------------
CREATE OR ALTER
PROC SP_CAPNHATTAIKHOAN
	@MATK VARCHAR(10),
	@USERID VARCHAR(100),
	@PASSWORD VARCHAR(100),
	@PASSWORDCHECK VARCHAR(100)
AS
BEGIN
	IF (@USERID = '' OR @PASSWORD = '' OR @PASSWORDCHECK = '')
	BEGIN
		PRINT N'Không cập nhật được thông tin tài khoản khi để trống'
		RETURN
	END
	IF EXISTS (SELECT '1' FROM TAIKHOAN WHERE TENTK = @USERID AND MATK <> @MATK)
	BEGIN
		PRINT N'Tên tài khoản đã tồn tại'
		RETURN
	END

	IF @PASSWORD <> @PASSWORDCHECK
	BEGIN
		PRINT N'Mật Khẩu và Nhập Lại Mật Khẩu không trùng khớp'
		RETURN
	END

	UPDATE TAIKHOAN
	SET TENTK = @USERID,
		MATKHAU = @PASSWORD
	WHERE MATK = @MATK
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO

