USE QLBH
GO
------------------------------------------------------------------------------------------------------------------
--TẠO ROLE
------------------------------------------------------------------------------------------------------------------
EXEC SP_ADDROLE 'R_ADMIN'
EXEC SP_ADDROLE 'R_NHANVIEN'
EXEC SP_ADDROLE 'R_DOITAC'
EXEC SP_ADDROLE 'R_KHACHHANG'
EXEC SP_ADDROLE 'R_TAIXE'
GO
------------------------------------------------------------------------------------------------------------------
--TẠO ADMIN
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MATK, 3, 10) AS INT)) FROM TAIKHOAN WHERE LOAITK = 0),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	IF (SELECT LOAITK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM) = 0
	BEGIN
		SET @TENTK  = (SELECT TENTK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM)
		SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	END
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO NHÂN VIÊN
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MATK, 3, 10) AS INT)) FROM TAIKHOAN WHERE LOAITK = 1),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	IF (SELECT LOAITK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM) = 1
	BEGIN
		SET @TENTK  = (SELECT TENTK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM)
		SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	END
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO NHÂN VIÊN
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MATK, 3, 10) AS INT)) FROM TAIKHOAN WHERE LOAITK = 1),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	IF (SELECT LOAITK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM) = 1
	BEGIN
		SET @TENTK  = (SELECT TENTK FROM TAIKHOAN WHERE CAST(SUBSTRING(MATK, 3, 10) AS INT) = @NUM)
		SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	END
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO ĐỐI TÁC
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MADT, 3, 10) AS INT)) FROM DOITAC),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	SET @TENTK  = (SELECT TK.TENTK FROM TAIKHOAN TK JOIN DOITAC DT ON TK.MATK = DT.MATK
					WHERE CAST(SUBSTRING(DT.MADT, 3, 10) AS INT) = @NUM)
	SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO KHÁCH HÀNG
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MAKH, 3, 10) AS INT)) FROM KHACHHANG),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	SET @TENTK  = (SELECT TK.TENTK FROM TAIKHOAN TK JOIN KHACHHANG KH ON TK.MATK = KH.MATK
					WHERE CAST(SUBSTRING(KH.MAKH, 3, 10) AS INT) = @NUM)
	SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO TÀI XẾ
------------------------------------------------------------------------------------------------------------------
DECLARE @TENTK VARCHAR(100),
		@MK VARCHAR(100),
		@MAX INT = (SELECT MAX(CAST(SUBSTRING(MATX, 3, 10) AS INT)) FROM TAIXE),
		@NUM INT = 0
WHILE @NUM <= @MAX
BEGIN
	SET @TENTK  = (SELECT TK.TENTK FROM TAIKHOAN TK JOIN TAIXE TX ON TK.MATK = TX.MATK
					WHERE CAST(SUBSTRING(TX.MATX, 3, 10) AS INT) = @NUM)
	SET @MK  = (SELECT MATKHAU FROM TAIKHOAN WHERE TENTK = @TENTK)
	IF @TENTK NOT IN (SELECT NAME FROM SYS.SQL_LOGINS)
	BEGIN
		EXEC SP_ADDLOGIN @TENTK, @MK,'QLBH'
	END
	SET @NUM += 1
END
GO
------------------------------------------------------------------------------------------------------------------
--TẠO USER
------------------------------------------------------------------------------------------------------------------
DECLARE @USERNAME VARCHAR(100),
		@LOGINNAME VARCHAR(100),
		@MAX INT = (SELECT MAX(principal_id) FROM SYS.SQL_LOGINS),
		@COUNT INT = 0
WHILE @COUNT <= @MAX
BEGIN
	SET @LOGINNAME = (SELECT NAME FROM SYS.SQL_LOGINS WHERE principal_id = @COUNT)
	IF @LOGINNAME IS NOT NULL 
	BEGIN
		IF @LOGINNAME IN (SELECT TENTK FROM TAIKHOAN)
		BEGIN
			IF (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @LOGINNAME) = 0
			BEGIN
				SET @USERNAME = (SELECT NV.MANV FROM NHANVIEN NV JOIN TAIKHOAN TK
								ON NV.MATK = TK.MATK
								WHERE TK.TENTK = @LOGINNAME)
				IF @USERNAME NOT IN (SELECT NAME FROM SYS.database_principals)
					EXEC SP_ADDUSER @LOGINNAME, @USERNAME, 'R_ADMIN'
			END
			ELSE IF (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @LOGINNAME) = 1
			BEGIN
				SET @USERNAME = (SELECT NV.MANV FROM NHANVIEN NV JOIN TAIKHOAN TK
								ON NV.MATK = TK.MATK
								WHERE TK.TENTK = @LOGINNAME)
				IF @USERNAME NOT IN (SELECT NAME FROM SYS.database_principals)
					EXEC SP_ADDUSER @LOGINNAME, @USERNAME, 'R_NHANVIEN'
			END
			ELSE IF (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @LOGINNAME) = 2
			BEGIN
				SET @USERNAME = (SELECT DT.MADT FROM DOITAC DT JOIN TAIKHOAN TK
								ON DT.MATK = TK.MATK
								WHERE TK.TENTK = @LOGINNAME)
				IF @USERNAME NOT IN (SELECT NAME FROM SYS.database_principals)
					EXEC SP_ADDUSER @LOGINNAME, @USERNAME, 'R_DOITAC'
			END
			ELSE IF (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @LOGINNAME) = 3
			BEGIN
				SET @USERNAME = (SELECT KH.MAKH FROM KHACHHANG KH JOIN TAIKHOAN TK
								ON KH.MATK = TK.MATK
								WHERE TK.TENTK = @LOGINNAME)
				IF @USERNAME NOT IN (SELECT NAME FROM SYS.database_principals)
					EXEC SP_ADDUSER @LOGINNAME, @USERNAME, 'R_KHACHHANG'
			END
			ELSE IF (SELECT LOAITK FROM TAIKHOAN WHERE TENTK = @LOGINNAME) = 4
			BEGIN
				SET @USERNAME = (SELECT TX.MATX FROM TAIXE TX JOIN TAIKHOAN TK
								ON TX.MATK = TK.MATK
								WHERE TK.TENTK = @LOGINNAME)
				IF @USERNAME NOT IN (SELECT NAME FROM SYS.database_principals)
					EXEC SP_ADDUSER @LOGINNAME, @USERNAME, 'R_TAIXE'
			END
		END
	END
	SET @COUNT += 1
END
GO

------------------------------------------------------------------------------------------------------------------
--CHỨC NĂNG DÙNG CHUNG
------------------------------------------------------------------------------------------------------------------
--ĐĂNG KÝ
GRANT INSERT ON TAIKHOAN TO R_TAIXE, R_KHACHHANG, R_DOITAC, R_ADMIN
GRANT EXECUTE ON DBO.SP_DANGKYTAIKHOAN TO R_TAIXE, R_KHACHHANG, R_DOITAC

--ĐĂNG NHẬP
GRANT EXECUTE ON DBO.SP_DANGNHAP TO R_TAIXE, R_KHACHHANG, R_DOITAC, R_NHANVIEN, R_ADMIN

--- CHỈNH SỬA THÔNG TIN TÀI KHOẢN
GRANT SELECT, INSERT, UPDATE ON NHANVIEN TO R_NHANVIEN, R_ADMIN
GRANT SELECT, INSERT, UPDATE ON DOITAC TO R_DOITAC
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO R_KHACHHANG
GRANT SELECT, INSERT, UPDATE ON TAIXE TO R_TAIXE
GRANT EXECUTE ON DBO.SP_CAPNHATTAIKHOAN TO R_TAIXE, R_KHACHHANG, R_DOITAC, R_NHANVIEN, R_ADMIN
------------------------------------------------------------------------------------------------------------------
--CÁC QUYỀN CỦA ADMIN
------------------------------------------------------------------------------------------------------------------
GRANT SELECT, UPDATE, DELETE ON  TAIKHOAN TO R_ADMIN
GRANT DELETE ON NHANVIEN TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_QUANLYTAIKHOAN TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_DANGKYNHANVIEN TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_XOANHANVIEN TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_NV_CAPNHATTHONGTINCHITIET TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_XEMTAIKHOANDADUOCKICHHOAT TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_KHOA TO R_ADMIN
GRANT EXECUTE ON DBO.SP_AD_KICHHOAT TO R_ADMIN

------------------------------------------------------------------------------------------------------------------
--CÁC QUYỀN CỦA NHÂN VIÊN
------------------------------------------------------------------------------------------------------------------
GRANT SELECT, UPDATE, DELETE ON HOPDONG TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_AD_NV_CAPNHATTHONGTINCHITIET TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_NV_XEMHOPDONGCHUADUYET TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_NV_XEMHOPDONGSAPHETHAN TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_NV_XEMHOPDONGDADUYET TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_NV_CAPNHATHOPDONG TO R_NHANVIEN 
GRANT EXECUTE ON DBO.SP_NV_XOAHOPDONG TO R_NHANVIEN
GRANT EXECUTE ON DBO.SP_NV_DUYETHOPDONG TO R_NHANVIEN 
GRANT EXECUTE ON DBO.SP_NV_TAIKYHOPDONG TO R_NHANVIEN
------------------------------------------------------------------------------------------------------------------
--CÁC QUYỀN CỦA ĐỐI TÁC
------------------------------------------------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON HOPDONG TO R_DOITAC
GRANT SELECT, INSERT, UPDATE, DELETE ON CUAHANG TO R_DOITAC
GRANT SELECT, INSERT, UPDATE, DELETE ON MONAN TO R_DOITAC
GRANT SELECT, UPDATE ON DONDATHANG TO R_DOITAC
GRANT SELECT ON CHITIETDONDATHANG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_CAPNHATCHITIET TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_DOANHSOBAN TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_CAPNHATHOPDONG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMHOPDONG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_THEMHOPDONG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMTHONGTINCUAHANG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_THEMCUAHANG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XOACUAHANG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_CAPNHATTHONGTINCUAHANG TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMMONAN TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_THEMMONAN TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XOAMONAN TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_CAPNHATTHONGTINMONAN TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMDONHANGCHUAXULY TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMDONHANGDAXULY TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_HOANTATCHUANBI TO R_DOITAC
GRANT EXECUTE ON DBO.SP_DT_XEMCHITIETDON TO R_DOITAC
------------------------------------------------------------------------------------------------------------------
--CÁC QUYỀN CỦA KHÁCH HÀNG
------------------------------------------------------------------------------------------------------------------
GRANT SELECT ON DOITAC TO R_KHACHHANG
GRANT SELECT ON MONAN TO R_KHACHHANG
GRANT SELECT, INSERT, DELETE ON DONDATHANG TO R_KHACHHANG
GRANT SELECT, INSERT, UPDATE ON CHITIETDONDATHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_CAPNHATKHACHHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMDONHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMCHITIETMONAN TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_DANHGIAMONAN TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMDOITAC TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMCUAHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMMONAN TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_THEMMONVAOGIOHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_HOANTHANHDONHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_HUYDON TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_KHOITAODON TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XOADON TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XEMGIOHANG TO R_KHACHHANG
GRANT EXECUTE ON DBO.SP_KH_XOAMON TO R_KHACHHANG
------------------------------------------------------------------------------------------------------------------
--CÁC QUYỀN CỦA TÀI XẾ
------------------------------------------------------------------------------------------------------------------
GRANT SELECT ON DOITAC TO R_TAIXE
GRANT SELECT ON MONAN TO R_TAIXE
GRANT SELECT ON KHACHHANG TO R_TAIXE
GRANT SELECT, UPDATE ON DONDATHANG TO R_TAIXE
GRANT SELECT ON CHITIETDONDATHANG TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_CAPNHATCHITIET TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_XEMDONHANG TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_NHANDON TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_HOANTHANHDON TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_XEMCHITIETDON TO R_TAIXE
GRANT EXECUTE ON DBO.USP_TX_XEMCHITIETTHUNHAP TO R_TAIXE
