USE QLBH
GO
--ĐỐI TÁC CẬP NHẬT THÔNG TIN CHI TIẾT---------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_CAPNHATCHITIET
	@MADT VARCHAR(10),
	@TENQUAN NVARCHAR(100),
	@EMAIL VARCHAR(100),
	@SDT VARCHAR(20),
	@DIACHITRUSOCHINH NVARCHAR(100),
	@SLCUAHANG INT,
	@SLDONMOINGAY VARCHAR(10),
	@LOAIAMTHUC NVARCHAR(100),
	@MASOTHUE VARCHAR(20)
AS
BEGIN
	IF EXISTS (SELECT '1' FROM DOITAC WHERE TENQUAN = @TENQUAN AND MADT <> @MADT)
	BEGIN
		PRINT N'Tên quán đã tồn tại'
		RETURN
	END
	IF (SELECT ISNUMERIC(@SDT)) = 0
	BEGIN
		PRINT N'Số Điện Thoại chỉ có số'
		RETURN
	END
	IF (SELECT ISNUMERIC(@MASOTHUE)) = 0
	BEGIN
		PRINT N'Mã số thuế chỉ có số'
		RETURN
	END

	UPDATE DOITAC
	SET TENQUAN = @TENQUAN,
		EMAIL = @EMAIL,
		SDT = @SDT,
		DIACHITRUSOCHINH = @DIACHITRUSOCHINH,
		SLCUAHANG = @SLCUAHANG,
		SLDONMOINGAY = @SLDONMOINGAY,
		LOAIAMTHUC = @LOAIAMTHUC,
		MASOTHUE = @MASOTHUE

		WHERE MADT = @MADT
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO
--ĐỐI TÁC CẬP NHẬT DOANH SỐ BÁN---------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_DOANHSOBAN
	@MADT VARCHAR(10)
AS
	DECLARE @DOANHSO MONEY = (SELECT SUM(DH.TONGTIEN) FROM DONDATHANG DH 
							JOIN (SELECT DISTINCT CT.MADH FROM CHITIETDONDATHANG CT WHERE CT.MADT = @MADT) AS DHANG ON DH.MADH = DHANG.MADH
							WHERE DH.TINHTRANG = N'Đã Hoàn Thành Đơn')

	UPDATE DOITAC
	SET DOANHSOBAN = @DOANHSO
	WHERE MADT = @MADT

	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
GO
--ĐỐI TÁC CẬP HỢP ĐỒNG---------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_CAPNHATHOPDONG
	@MADT VARCHAR(10),
	@STK VARCHAR(20),
	@NH VARCHAR(10),
	@CN VARCHAR(20)
AS
	IF (SELECT ISNUMERIC(@STK)) = 0
	BEGIN
		PRINT N'Số tài khoản chỉ có số'
		RETURN
	END

	UPDATE HOPDONG
	SET SOTAIKHOAN = @STK,
		NGANHANG = @NH,
		CHINHANHNGANHANG = @CN
	WHERE MADT = @MADT

	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
GO
--ĐỐI TÁC XEM HỢP ĐỒNG---------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XEMHOPDONG
	@MADT VARCHAR(10)
AS
BEGIN
	SELECT HD.*, DT.TENQUAN, DT.MASOTHUE, DT.DIACHITRUSOCHINH, DT.MASOTHUE, DT.NGUOIDAIDIEN, DT.SLCUAHANG FROM HOPDONG HD JOIN DOITAC DT ON HD.MADT = DT.MADT
	WHERE HD.MADT = @MADT
END
GO
--ĐỐI TÁC THÊM HỢP ĐỒNG
CREATE OR ALTER
PROC SP_DT_THEMHOPDONG
	@MADT VARCHAR(10),
	@STK VARCHAR(20),
	@NH VARCHAR(10),
	@CNNH VARCHAR(20)
AS
BEGIN
	IF @STK = '' OR @NH = '' OR @CNNH = ''
	BEGIN
		PRINT N'Không nhập đầy đủ thông tin để đăng ký'
		RETURN
	END

	IF NOT EXISTS (SELECT '1' FROM DOITAC WHERE MADT = @MADT)
	BEGIN
		PRINT N'Đối tác không tồn tại'
		RETURN
	END

	--TẠO MÃ HỢP ĐỒNG
	DECLARE @MAHD VARCHAR(10) = 'HD'
	WHILE @MAHD = 'HD' OR @MAHD IN ( SELECT MAHD FROM HOPDONG)
	BEGIN
		 SET @MAHD += CAST((FLOOR(RAND()*(100000-0+1)+0)) AS VARCHAR(8))
	END

	--THÊM HỢP ĐỒNG
	INSERT INTO HOPDONG VALUES(@MAHD,NULL,NULL,N'Chưa Duyệt',@STK,@NH,@CNNH,NULL,@MADT,NULL)
	IF @@ERROR <> 0 
		PRINT N'Đăng ký không thành công'
	ELSE
		PRINT N'Đăng ký thành công'
END
GO
--ĐỐI TÁC XEM THÔNG TIN CỬA HÀNG ---------------------------------------------------------
CREATE  OR ALTER 
PROC SP_DT_XEMTHONGTINCUAHANG 
	@MADT VARCHAR(10)
AS
BEGIN
	SELECT STT, TEN, DIACHI, THOIGIANMOCUA, THOIGIANDONGCUA, CAST(TINHTRANG AS INT) AS TINHTRANG
	FROM CUAHANG
	WHERE MADT = @MADT
END
GO

--ĐỐI TÁC THÊM CỬA HÀNG ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_THEMCUAHANG
	@MADT VARCHAR(10),
	@TENMOI NVARCHAR(100),
	@STT INT,
	@DIACHI NVARCHAR(100),
	@THOIGIANMOCUA TIME,
	@THOIGIANDONGCUA TIME,
	@TINHTRANG BIT
AS
BEGIN
	--TẠO MÃ CỬA HÀNG
	IF @STT IS NULL
		SET @STT = (SELECT MAX(STT) FROM CUAHANG WHERE MADT = @MADT) + 1
	

	--THÊM CỬA HÀNG
	INSERT INTO CUAHANG VALUES(@MADT,@STT,@TENMOI, @DIACHI,@THOIGIANMOCUA,@THOIGIANDONGCUA, @TINHTRANG)
	IF @@ERROR <> 0 
		PRINT N'Thêm cửa hàng không thành công'
	ELSE
		PRINT N'Thêm cửa hàng thành công'
END
GO

--ĐỐI TÁC XÓA CỬA HÀNG ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XOACUAHANG
	@STT VARCHAR(10),
	@MADT VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM CUAHANG WHERE STT = @STT AND MADT = @MADT)
	BEGIN
		PRINT N'Cửa hàng không tồn tại'
		RETURN
	END

	DELETE FROM CUAHANG WHERE STT = @STT AND MADT = @MADT
	
	IF @@ERROR <> 0 
		PRINT N'Xóa cửa hàng không thành công'
	ELSE
		PRINT N'Xóa cửa hàng thành công'
END
GO

--ĐỐI TÁC CẬP NHẬT THÔNG TIN CỬA HÀNG ---------------------------------------------------------
CREATE  OR ALTER 
PROC SP_DT_CAPNHATTHONGTINCUAHANG 
	@MADT VARCHAR(10),
	@STT INT,
	@TENMOI NVARCHAR(100),
	@DIACHI NVARCHAR(100),
	@THOIGIANMOCUA TIME,
	@THOIGIANDONGCUA TIME,
	@TINHTRANG BIT
AS
BEGIN

	UPDATE CUAHANG
	SET	TEN = @TENMOI,
		DIACHI = @DIACHI,
		THOIGIANMOCUA = @THOIGIANMOCUA,
		THOIGIANDONGCUA = @THOIGIANDONGCUA,
		TINHTRANG = @TINHTRANG
		WHERE MADT = @MADT AND STT = @STT
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO

--ĐỐI TÁC XEM MÓN ĂN ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XEMMONAN
	@MADT VARCHAR(10)
AS
BEGIN

	SELECT MAMA, TENMONAN, MIEUTAMON, GIA, TINHTRANG, TUYCHON
	FROM MONAN
	WHERE MADT = @MADT
END
GO

--ĐỐI TÁC THÊM MÓN ĂN ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_THEMMONAN
	@MADT VARCHAR(10),
	@TEN NVARCHAR(100),
	@MIEUTAMON NVARCHAR(100),
	@GIA MONEY,
	@TINHTRANG NVARCHAR(100),
	@TUYCHON NVARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT '1' FROM MONAN WHERE TENMONAN = @TEN AND MADT = @MADT)
	BEGIN
		PRINT N'Tên món ăn đã tồn tại'
		RETURN
	END

	IF @MADT = '' OR @TEN = '' OR @GIA = '' OR @TINHTRANG = ''
	BEGIN
		PRINT N'Không nhập đầy đủ thông tin để thêm món ăn'
		RETURN
	END

	--TẠO MÃ MÓN ĂN
	DECLARE @MAMA VARCHAR(10) = 'MA'
	WHILE @MAMA = 'MA' OR @MAMA IN ( SELECT MAMA FROM MONAN)
	BEGIN
		 SET @MAMA += CAST((FLOOR(RAND()*(100000-0+1)+0)) AS VARCHAR(98))
	END
	

	--THÊM MÓN ĂN
	INSERT INTO MONAN VALUES(@MAMA,@MADT,@TEN,@MIEUTAMON,@GIA, @TINHTRANG, @TUYCHON)
	
	IF @@ERROR <> 0 
		PRINT N'Thêm món ăn không thành công'
	ELSE
		PRINT N'Thêm món ăn thành công'
END
GO

--ĐỐI TÁC XÓA MÓN ĂN ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XOAMONAN
	@MAMA VARCHAR(10),
	@MADT VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM MONAN WHERE MAMA = @MAMA AND MADT = @MADT)
	BEGIN
		PRINT N'Món ăn không tồn tại'
		RETURN
	END

	DELETE FROM MONAN WHERE MAMA = @MAMA AND MADT = @MADT
	
	IF @@ERROR <> 0 
		PRINT N'Xóa món ăn không thành công'
	ELSE
		PRINT N'Xóa món ăn thành công'
END
GO

--ĐỐI TÁC CẬP NHẬT THÔNG TIN MÓN ĂN ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_CAPNHATTHONGTINMONAN
	@MAMA VARCHAR(10),
	@MADT VARCHAR(10),
	@TENMONAN NVARCHAR(100),
	@MIEUTAMON NVARCHAR(100),
	@GIA MONEY,
	@TINHTRANG NVARCHAR(100),
	@TUYCHON NVARCHAR(100)
AS
BEGIN
	IF EXISTS (SELECT '1' FROM MONAN WHERE TENMONAN = @TENMONAN AND MADT = @MADT AND MAMA <> @MAMA)
	BEGIN
		PRINT N'Tên món ăn đã tồn tại'
		RETURN
	END

	UPDATE MONAN
	SET	TENMONAN = @TENMONAN,
		MIEUTAMON = @MIEUTAMON,
		GIA = @GIA,
		TINHTRANG = @TINHTRANG,
		TUYCHON = @TUYCHON
		WHERE MADT = @MADT AND MAMA = @MAMA
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO

--ĐỐI TÁC XEM ĐƠN HÀNG CHƯA XỬ LÝ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XEMDONHANGCHUAXULY
	@MADT VARCHAR(10)
AS
BEGIN
	
	SELECT DH.MADH, KH.TEN, KH.SDT, DH.HINHTHUCTHANHTOAN, DH.TINHTRANG, DBO.UF_TONGTIEN(DH.MADH) AS TONGTIEN FROM DONDATHANG DH, KHACHHANG KH
	WHERE DH.MADH IN (SELECT DISTINCT MADH FROM CHITIETDONDATHANG WHERE MADT = @MADT) AND TINHTRANG = N'Tiếp Nhận'
END
GO

--ĐỐI TÁC XEM ĐƠN HÀNG ĐÃ XỬ LÝ------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XEMDONHANGDAXULY
	@MADT VARCHAR(10)
AS
BEGIN
	
	SELECT DH.MADH, KH.TEN, KH.SDT, DH.HINHTHUCTHANHTOAN, DH.TINHTRANG, DBO.UF_TONGTIEN(DH.MADH) AS TONGTIEN FROM DONDATHANG DH, KHACHHANG KH
	WHERE DH.MADH IN (SELECT DISTINCT MADH FROM CHITIETDONDATHANG WHERE MADT = @MADT) AND TINHTRANG = N'Đã Hoàn Thành Đơn'
END
GO
--ĐỐI TÁC NHẬN ĐƠN------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_HOANTATCHUANBI
	@MADH VARCHAR(10),
	@MADT VARCHAR(10)
AS
	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH)
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE TINHTRANG = N'Tiếp Nhận' AND MADH = @MADH)
	BEGIN
		PRINT N'Đơn Hàng chưa được nhận'
		RETURN
	END
	UPDATE DONDATHANG
	SET TINHTRANG = N'Đang Giao'
	WHERE MADH = @MADH
	
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
GO

--ĐỐI TÁC XEM CHI TIẾT MÓN ĂN TRONG ĐƠN------------------------------------------------------------------------------------
CREATE OR ALTER
PROC SP_DT_XEMCHITIETDON
	@MADH VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH)
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END
	SELECT MA.TENMONAN, CT.SLMON
	FROM CHITIETDONDATHANG CT JOIN MONAN MA ON CT.MADT = MA.MADT AND CT.MAMA = MA.MAMA
	WHERE MADH = @MADH
END