USE QLBH
GO

--TÀI XẾ CẬP NHẬT THÔNG TIN CHI TIẾT---------------------------------------------------------
CREATE OR ALTER
PROC USP_TX_CAPNHATCHITIET
	@MATX VARCHAR(10),
	@TEN NVARCHAR(100),
	@SDT VARCHAR(20),
	@DC NVARCHAR(100),
	@CMND VARCHAR(20),
	@BSX CHAR(9),
	@KHUVUCHD NVARCHAR(100),
	@STK VARCHAR(20),
	@NH VARCHAR(100),
	@EMAIL VARCHAR(100),
	@CNNH VARCHAR(20)
AS
BEGIN
	IF EXISTS (SELECT '1' FROM TAIXE WHERE CMND = @CMND AND MATX <> @MATX)
	BEGIN
		PRINT N'Chứng Minh Nhân Dân đã tồn tại'
		RETURN
	END

	IF (SELECT ISNUMERIC(@SDT)) = 0
	BEGIN
		PRINT N'Số Điện Thoại chỉ có số'
		RETURN
	END

	IF (SELECT ISNUMERIC(@CMND)) = 0
	BEGIN
		PRINT N'Chứng Minh Nhân Dân chỉ có số'
		RETURN
	END

	IF (SELECT ISNUMERIC(@STK)) = 0
	BEGIN
		PRINT N'Số Tài Khoản chỉ có số'
		RETURN
	END

	UPDATE TAIXE
	SET TEN = @TEN,
		SDT = @SDT,
		DIACHI = @DC,
		CMND = @CMND,
		BIENSOXE = @BSX,
		KHUVUCHOATDONG = @KHUVUCHD,
		EMAIL = @EMAIL,
		SOTAIKHOAN = @STK,
		NGANHANG = @NH,
		CHINHANHNGANHANG = @CNNH
	WHERE MATX = @MATX
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO

--TÀI XẾ XEM ĐƠN HÀNG------------------------------------------------------------------------------------
CREATE OR ALTER
PROC USP_TX_XEMDONHANG
	@MADH VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH)
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END
	
	SELECT DH.MADH, KH.TEN, KH.SDT, KH.DIACHI, DH.PHIVANCHUYEN, DH.HINHTHUCTHANHTOAN, DH.TINHTRANG, DBO.UF_TONGTIEN(@MADH) AS TONGTIEN FROM DONDATHANG DH, KHACHHANG KH
	WHERE DH.MADH = @MADH AND DH.NGUOIDAT = KH.MAKH
END
GO

--TÀI XẾ NHẬN ĐƠN------------------------------------------------------------------------------------
CREATE OR ALTER
PROC USP_TX_NHANDON
	@MADH VARCHAR(10),
	@MATX VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	IF EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH AND TINHTRANG = N'Đã Huỷ')
	BEGIN
		PRINT N'Đơn Hàng đã bị huỷ'
		RETURN
	END

	UPDATE DONDATHANG
	SET TINHTRANG = N'Tiếp Nhận',
		NGUOIGIAO = @MATX
	WHERE MADH = @MADH
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO

--TÀI XẾ HOÀN THÀNH ĐƠN------------------------------------------------------------------------------------
CREATE OR ALTER
PROC USP_TX_HOANTHANHDON
	@MADH VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH AND TINHTRANG = N'Đang Giao')
	BEGIN
		PRINT N'Đơn Hàng chưa được tiếp nhận'
		RETURN
	END

	UPDATE DONDATHANG
	SET TINHTRANG = N'Đã Hoàn Thành Đơn'
	WHERE MADH = @MADH
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
END
GO
--TÀI XẾ XEM CHI TIẾT MÓN ĂN TRONG ĐƠN------------------------------------------------------------------------------------
CREATE OR ALTER
PROCEDURE USP_TX_XEMCHITIETDON
	@MADH VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	SELECT MA.TENMONAN, CT.SLMON, MA.GIA , CH.TEN, CH.DIACHI
	FROM CHITIETDONDATHANG CT JOIN MONAN MA ON CT.MADT = MA.MADT AND CT.MAMA = MA.MAMA JOIN CUAHANG CH ON CH.MADT = CT.MADT
	WHERE MADH = @MADH
END
GO

--TÀI XẾ XEM CHI TIẾT THU NHẬP------------------------------------------------------------------------------------
CREATE OR ALTER
PROC USP_TX_XEMCHITIETTHUNHAP
	@MADH VARCHAR(10),
	@MATX VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	IF NOT EXISTS (SELECT '1' FROM TAIXE WHERE MATX = @MATX )
	BEGIN
		PRINT N'Tài Xế không tồn tại'
		RETURN
	END

	SELECT MADH, PHIVANCHUYEN, THOIGIAN, (SELECT SUM(PHIVANCHUYEN) FROM DONDATHANG WHERE NGUOIGIAO = @MATX AND TINHTRANG = N'Đã Hoàn Thành Đơn') AS TONGTHUNHAP
	FROM DONDATHANG
	WHERE MADH = @MADH AND NGUOIGIAO = @MATX AND TINHTRANG = N'Đã Hoàn Thành Đơn'

END
GO
