USE QLBH
GO
--Tính Tổng Tiền Đơn Hàng
CREATE OR ALTER
FUNCTION UF_TONGTIEN (@MADH VARCHAR(10))
RETURNS MONEY
AS
BEGIN
	RETURN (SELECT PHIVANCHUYEN FROM DONDATHANG WHERE MADH = @MADH) + 
			(SELECT SUM(MA.GIA * CT.SLMON)
			FROM CHITIETDONDATHANG CT 
			JOIN MONAN MA ON CT.MAMA = MA.MAMA AND CT.MADT = MA.MADT
			WHERE CT.MADH = @MADH)
END
GO
-- CẬP NHẬP KHÁCH HÀNG
CREATE OR ALTER 
PROC SP_KH_CAPNHATKHACHHANG
	@MAKH VARCHAR(10),
	@TEN NVARCHAR(100),
	@DIACHI NVARCHAR(100),
	@SDT VARCHAR(20),
	@EMAIL VARCHAR(100)
AS
	IF (SELECT ISNUMERIC(@SDT)) = 0
	BEGIN
		PRINT N'Số Điện Thoại chỉ có số'
		RETURN
	END
	UPDATE KHACHHANG
	SET TEN = @TEN,
		EMAIL = @EMAIL,
		SDT = @SDT,
		DIACHI = @DIACHI
	WHERE MAKH = @MAKH
	IF @@ERROR <> 0 
		PRINT N'Cập nhật không thành công'
	ELSE
		PRINT N'Cập nhật thành công'
GO
--KHÁCH HÀNG XEM ĐƠN HÀNG 
CREATE OR ALTER
PROC SP_KH_XEMDONHANG
	@MAKH VARCHAR(10)
AS
BEGIN
	SELECT MADH, THOIGIAN, PHIVANCHUYEN, HINHTHUCTHANHTOAN, TINHTRANG, DBO.UF_TONGTIEN(MADH) AS TONGTIEN FROM DONDATHANG
	WHERE NGUOIDAT = @MAKH
END

--KHÁCH HÀNG XEM CHI TIẾT MÓN ĂN
GO
CREATE OR ALTER
PROC SP_KH_XEMCHITIETMONAN
	@MADH VARCHAR(10)
AS

BEGIN
	IF NOT EXISTS (SELECT '1' FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END
	SELECT DISTINCT MA.TENMONAN, CT.SLMON, MA.GIA , CH.TEN, CT.DANHGIA
	FROM CHITIETDONDATHANG CT JOIN MONAN MA ON CT.MADT = MA.MADT AND CT.MAMA = MA.MAMA JOIN CUAHANG CH ON CH.MADT = CT.MADT
END
GO

-- KHÁCH HÀNG ĐÁNH GIÁ MÓN ĂN
CREATE OR ALTER
PROC SP_KH_DANHGIAMONAN
	@MADH VARCHAR(10),
	@TENMON NVARCHAR(100),
	@TENQUAN NVARCHAR(100),
	@DANHGIA NVARCHAR(100)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'ĐƠN HÀNG KHÔNG TỒN TẠI'
		RETURN
	END
	UPDATE CHITIETDONDATHANG
	SET DANHGIA = @DANHGIA 
	WHERE MADH = @MADH AND MAMA = (SELECT MA.MADT FROM MONAN MA JOIN DOITAC DT ON MA.MADT = DT.MADT WHERE MA.TENMONAN = @TENMON AND DT.TENQUAN = @TENQUAN)
	AND MADT = (SELECT MA.MADT FROM MONAN MA JOIN DOITAC DT ON MA.MADT = DT.MADT WHERE MA.TENMONAN = @TENMON AND DT.TENQUAN = @TENQUAN)
END

GO
-- KHÁCH HÀNG XEM DANH SÁCH ĐỐI TÁC TRƯỚC KHI ĐẶT MÓN
CREATE OR ALTER
PROC SP_KH_XEMDOITAC
	@MADT VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM DOITAC WHERE MADT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG TỒN TẠI'
		RETURN
	END
	SELECT DT.TENQUAN, DT.SDT, DT.DIACHITRUSOCHINH, DT.SLCUAHANG, DT.LOAIAMTHUC FROM DOITAC DT WHERE DT.MADT = @MADT
END
GO
-- KHACH HANG XEM DANH SACH CỬA HÀNG
CREATE OR ALTER 
PROC SP_KH_XEMCUAHANG
	@MADT VARCHAR(10),
	@STT INT
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM DOITAC WHERE MADT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG TỒN TẠI'
		RETURN
	END
	DECLARE @TT NVARCHAR(50) = (SELECT CAST(TINHTRANG AS CHAR(1)) FROM CUAHANG WHERE MADT = @MADT AND STT = @STT)
	IF @TT = 1
		SET @TT = N'Bình Thường'
	ELSE 
		SET @TT = N'Tạm Ngưng'
	SELECT TEN, DIACHI,  THOIGIANMOCUA, THOIGIANDONGCUA, @TT FROM CUAHANG  WHERE MADT = @MADT AND STT = @STT
END
GO

--KHÁCH HÀNG XEM MÓN ĂN
CREATE OR ALTER 
PROC SP_KH_XEMMONAN
	@MADT VARCHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT '1' FROM DOITAC WHERE MADT = @MADT)
	BEGIN
		PRINT N'ĐỐI TÁC KHÔNG TỒN TẠI'
		RETURN
	END
	SELECT  MAMA, TENMONAN, MIEUTAMON, GIA, TINHTRANG  FROM MONAN  WHERE MADT = @MADT
END
GO

--KHÁCH HÀNG XEM GIỎ HÀNG
CREATE OR ALTER 
PROC SP_KH_XEMGIOHANG
	@MADH VARCHAR(10)
AS
BEGIN
	SELECT MA.MAMA, MA.TENMONAN, MA.GIA, CT.SLMON from CHITIETDONDATHANG CT JOIN MONAN MA ON CT.MAMA = MA.MAMA AND CT.MADT = MA.MADT
	WHERE CT.MADH = @MADH
END
GO

--KHÁCH HÀNG KHỞI TẠO MÃ ĐƠN HÀNG
CREATE OR ALTER 
PROC SP_KH_KHOITAODON
	@MAKH VARCHAR(10)
AS
	IF NOT EXISTS (SELECT '1' FROM KHACHHANG WHERE MAKH = @MAKH)
	BEGIN
		PRINT N'KHÁCH HÀNG KHÔNG TỒN TẠI'
		RETURN
	END
	DECLARE @MADH VARCHAR(10) = 'DH'
	WHILE @MADH = 'DH' OR @MADH IN ( SELECT MADH FROM DONDATHANG)
	BEGIN
		 SET @MADH += CAST((FLOOR(RAND()*(100000-0+1)+0)) AS VARCHAR(98))
	END
	INSERT INTO DONDATHANG(MADH,TINHTRANG,NGUOIDAT) VALUES(@MADH,N'Đang Đặt', @MAKH)
	SELECT MADH FROM DONDATHANG WHERE TINHTRANG = N'Đang Đặt' AND MADH = @MADH
	IF @@ERROR <> 0 
		PRINT N'ĐẶT HÀNG KHÔNG THÀNH CÔNG'
	ELSE
		PRINT N'ĐẶT HÀNG THÀNH CÔNG'
GO


GO
--KHÁCH HÀNG THÊM MÓN VÀO GIỎ
CREATE OR ALTER 
PROC SP_KH_THEMMONVAOGIOHANG
	@MADH VARCHAR(10),
	@MAMA VARCHAR(10),
	@MADT VARCHAR(10)
AS
	IF NOT EXISTS (SELECT '1' FROM MONAN WHERE MAMA = @MAMA AND MADT = @MADT)
	BEGIN
		PRINT N'MÓN ĂN KHÔNG TỒN TẠI'
		RETURN
	END
	IF(SELECT TINHTRANG FROM MONAN WHERE MAMA = @MAMA AND MADT = @MADT) <> N'Có Bán'
	BEGIN
		PRINT N'MÓN ĂN HẾT HÀNG'
		RETURN
	END

	IF EXISTS (SELECT * FROM CHITIETDONDATHANG WHERE MADH = @MADH AND MAMA = @MAMA AND MADT = @MADT)
	BEGIN
		DECLARE @SL INT = (SELECT SLMON FROM CHITIETDONDATHANG WHERE MADH = @MADH AND MAMA = @MAMA AND MADT = @MADT)
		UPDATE CHITIETDONDATHANG
		SET SLMON += 1
		WHERE MADH = @MADH AND MAMA = @MAMA AND MADT = @MADT
	END
	ELSE IF NOT EXISTS (SELECT MADH FROM CHITIETDONDATHANG WHERE MADH = @MADH AND MAMA = @MAMA AND MADT = @MADT)
	BEGIN
		INSERT INTO CHITIETDONDATHANG VALUES(@MADH, @MAMA, @MADT, 1, NULL)
	END
	ELSE IF @MADT <> (SELECT MADT FROM CHITIETDONDATHANG WHERE MADT <> @MADT AND MADH = @MADH)
	BEGIN
		ROLLBACK
		RETURN
	END
	IF @@ERROR <> 0 
		PRINT N'ĐẶT HÀNG KHÔNG THÀNH CÔNG'
	ELSE
		PRINT N'ĐẶT HÀNG THÀNH CÔNG'
GO
-- KHÁCH HÀNG ĐẶT ĐƠN HÀNG
CREATE OR ALTER 
PROC SP_KH_HOANTHANHDONHANG
	@MADH VARCHAR(10),
	@HINHTHUCTHANHTOAN NVARCHAR(100),
	@MAKH VARCHAR(10)
AS
	IF @HINHTHUCTHANHTOAN = ''
	BEGIN
		PRINT N'HÌNH THỨC THANH TOÁN KHÔNG ĐƯỢC TRỐNG'
		RETURN
	END
	UPDATE DONDATHANG
	SET TINHTRANG = N'Chờ Nhận',
		HINHTHUCTHANHTOAN = @HINHTHUCTHANHTOAN,
		PHIVANCHUYEN = 20000,
		TONGTIEN = DBO.UF_TONGTIEN(@MADH),
		THOIGIAN = GETDATE(),
		PHANTRAMHOAHONG = 20,
		NGUOIDAT = @MAKH
	WHERE MADH = @MADH
	IF @@ERROR <> 0 
		PRINT N'ĐẶT HÀNG KHÔNG THÀNH CÔNG'
	ELSE
		PRINT N'ĐẶT HÀNG THÀNH CÔNG'
GO

-- HỦY ĐƠN HÀNG
CREATE OR ALTER
PROC SP_KH_HUYDON
	@MaDH VARCHAR(10)
AS
	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END

	IF EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH AND TINHTRANG <> N'Chờ Nhận')
	BEGIN
		PRINT N'Đơn hàng đã được tiếp nhận'
		RETURN
	END
	UPDATE DONDATHANG
	SET TINHTRANG = N'Đã Huỷ'
	WHERE MADH = @MADH
GO

-- XOÁ ĐƠN ĐANG KHỞI TẠO
CREATE OR ALTER
PROC SP_KH_XOADON
	@MADH VARCHAR(10)
AS
	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END
	DELETE FROM CHITIETDONDATHANG WHERE MADH = @MADH
	DELETE FROM DONDATHANG WHERE MADH = @MADH
GO
-- XOÁ MÓN
CREATE OR ALTER
PROC SP_KH_XOAMON
	@MAMA VARCHAR(10),
	@MADH VARCHAR(10),
	@MADT VARCHAR(10)
AS
	IF NOT EXISTS (SELECT * FROM MONAN WHERE MAMA = @MAMA AND MADT = @MADT)
	BEGIN
		PRINT N'Món Ăn không tồn tại'
		RETURN
	END
	IF NOT EXISTS (SELECT * FROM DONDATHANG WHERE MADH = @MADH )
	BEGIN
		PRINT N'Đơn Hàng không tồn tại'
		RETURN
	END
	DELETE FROM CHITIETDONDATHANG WHERE MADH = @MADH AND MADT = @MADT AND MAMA = @MAMA
GO