USE QLBH
GO

--TRIGGER 1
CREATE OR ALTER TRIGGER MA_TENMONKHONGTRUNG
ON MONAN
FOR INSERT, UPDATE 
AS
BEGIN
	IF(UPDATE(TENMONAN))
	BEGIN
		IF EXISTS (SELECT * FROM MONAN MA JOIN INSERTED I ON MA.MAMA <> I.MAMA AND I.MADT = MA.MADT AND MA.TENMONAN = I.TENMONAN )
		BEGIN
			RAISERROR ('Tên món không được trùng',16,1)
			ROLLBACK
		END
	END
END
GO

--TRIGGER 2
CREATE OR ALTER TRIGGER MA_CTDH_TINHTRANGCOBAN
ON MONAN
FOR INSERT, UPDATE
AS
BEGIN
	IF(UPDATE(TINHTRANG))
	BEGIN
		IF EXISTS (SELECT MA.TINHTRANG FROM MONAN MA JOIN CHITIETDONDATHANG CT ON MA.MAMA = CT.MAMA AND MA.MADT = CT.MADT JOIN INSERTED I ON MA.MAMA = I.MAMA AND I.MADT = MA.MADT WHERE MA.TINHTRANG <> N'Có Bán')
		BEGIN
			RAISERROR ('Đã hết hàng',16,1)
			ROLLBACK
		END
	END
END
GO


--TRIGGER 3
CREATE OR ALTER TRIGGER HD_THOIGIANBATDAU_BE_THOIGIANKETTHUC 
ON HOPDONG
FOR INSERT , UPDATE 
AS
BEGIN
	DECLARE @NGAYBD DATE
	DECLARE @NGAYKETTHUC DATE
	SELECT @NGAYBD=I.NGAYBATDAU FROM inserted I
	SELECT @NGAYKETTHUC =I.NGAYKETTHUC FROM inserted I
	IF (@NGAYBD >@NGAYKETTHUC)
	BEGIN
		RAISERROR('Ngày Bắt đầu và kết thúc hợp đồng không hợp lệ',16,1)
		ROLLBACK
	END
END
